//> include:.
//> lib:.
//> cflags: -I. -L.
//> link:-l cfltk2 -l fltk  -l fltk_gl   -l user32 -l shell32 -l gdi32  -l winspool -l opengl32 -l glu32 -l gdiplus -l ole32 -l oleaut32  -l imm32 -l uuid  -l comctl32 -l comdlg32  -l stdc++.dll
#include <cfltk2/cfl.h> 
#include <cfltk2/cfl_box.h>
#include <cfltk2/cfl_button.h>
#include <cfltk2/cfl_draw.h>
#include <cfltk2/cfl_enums.h>
#include <cfltk2/cfl_group.h>
#include <cfltk2/cfl_image.h> 
#include <cfltk2/cfl_widget.h>
#include <cfltk2/cfl_window.h>
#include <stdio.h>
#include <stdlib.h>

let en = "english: The quick brown fox jumps over the lazy dog.";
let de = "german: Zwölf Boxkämpfer jagten Eva quer über den Sylter Deich.";
let ru = "russian: В чащах юга жил бы цитрус? Да, но фальшивый экземпляр!";
let gr = "greek: Γαζέες καὶ μυρτιὲς δὲν θὰ βρῶ πιὰ στὸ χρυσαφὶ ξέφωτο";
let fr = "french: Le cœur déçu mais l'âme plutôt naïve, Louÿs rêva de crapaüter ....";
let tk = "turkish: Pijamalı hasta, yağız şoföre çabucak güvendi.";
let multi="¡Hola Mundo!Γειά σου Κόσμε!Привет, мир!こんにちは世界！你好世界！नमस्ते दुनिया!👋🌎!";

fn  main()
{

    let win = Fl_Window_new(100,100,640,300,"नमस्ते दुनिया!👋🌎!");
    let h=Fl_Widget_height((Fl_Widget*)win)/7;
    let w=Fl_Widget_width((Fl_Widget*)win);//Fl_WidgetGetH(win)\6, w=Fl_WidgetGetW(win)
    Fl_Box_new(0,h*0,w,h,en);
    Fl_Box_new(0,h*1,w,h,de);
    Fl_Box_new(0,h*2,w,h,ru);
    Fl_Box_new(0,h*3,w,h,gr);
    Fl_Box_new(0,h*4,w,h,fr);
    Fl_Box_new(0,h*5,w,h,tk);
    Fl_Box_new(0,h*6,w,h,multi);
    
    Fl_Window_end(win);
    Fl_Window_show(win);
    Fl_run();
}
